/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.Person;
import model.System;
/**
 *
 * @author sirip
 */
public class EncounterHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EncounterHistoryJPanel
     */
    private JPanel displayPanel;
    private System system;
    private Person person;
    
    public EncounterHistoryJPanel(JPanel displayJpanel, System system, Person person) {
        this.displayPanel = displayPanel;
        this.system=system;
        this.person=person;
        initComponents();
        populateTable();
    }
    
    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblEncounterHistory.getModel();
        model.setRowCount(0);
        
        EncounterHistory encounterHistory = person.getPatient().getEncounterHistory();
        ArrayList<Encounter> encounters = encounterHistory.getEncounterHistory();
        
        for(Encounter encounter:encounters) {
            
            Object[] row = new Object[9];
            row[0] = encounter.getVitalSigns();
            row[1] = encounter.getVitalSigns().getPulse();
            row[2] = encounter.getVitalSigns().getBloodPressure();
            row[3] = encounter.getVitalSigns().getRespirationRate();
            row[4] = encounter.getVitalSigns().getSpo2();
            row[5] = encounter.getVitalSigns().getBmi();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounterHistory = new javax.swing.JTable();
        lblHeadingEncounterHistory = new javax.swing.JLabel();
        lblAdd = new javax.swing.JButton();
        lblViewUpdate = new javax.swing.JButton();
        lblDelete = new javax.swing.JButton();

        tblEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Temperature", "Pulse", "Blood Pressure", "Respiration Rate", "SpO2", "BMI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEncounterHistory);

        lblHeadingEncounterHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeadingEncounterHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeadingEncounterHistory.setText("Patient Encounter History");

        lblAdd.setText("Add");

        lblViewUpdate.setText("View/Update");

        lblDelete.setText("Delete");
        lblDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblHeadingEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAdd)
                        .addGap(18, 18, 18)
                        .addComponent(lblViewUpdate)
                        .addGap(27, 27, 27)
                        .addComponent(lblDelete)
                        .addGap(60, 60, 60))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblHeadingEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdd)
                    .addComponent(lblViewUpdate)
                    .addComponent(lblDelete))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lblAdd;
    private javax.swing.JButton lblDelete;
    private javax.swing.JLabel lblHeadingEncounterHistory;
    private javax.swing.JButton lblViewUpdate;
    private javax.swing.JTable tblEncounterHistory;
    // End of variables declaration//GEN-END:variables
}
