/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.City;
import model.CityList;
import model.Community;
import model.System;

/**
 *
 * @author sirip
 */
public class ViewCommunityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCommunityJPanel
     */
    private JPanel displayJPanel;
    private System system;
    private Community community;
    
    public ViewCommunityJPanel(JPanel displayJPanel, System system, Community community) {
        this.displayJPanel = displayJPanel;
        this.system = system;
        this.community = community;
        initComponents();
        displayData();
    }
    private void displayData() {    
        txtViewCommunity.setText(community.getCommunityName());
    }
    
    String regxCommunityName = "^[a-zA-Z\\s]+$";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewCommunityJLabel = new javax.swing.JLabel();
        communityNameJLabel = new javax.swing.JLabel();
        txtViewCommunity = new javax.swing.JTextField();
        btnUpdateCommunity = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        viewCommunityJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewCommunityJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewCommunityJLabel.setText("View/Update Community");

        communityNameJLabel.setText("Community Name :");

        btnUpdateCommunity.setText("Update");
        btnUpdateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCommunityActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewCommunityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(communityNameJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(txtViewCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(btnUpdateCommunity)))
                .addGap(323, 323, 323))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCommunityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityNameJLabel)
                    .addComponent(txtViewCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateCommunity)
                .addGap(181, 181, 181))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCommunityActionPerformed
        // TODO add your handling code here:

//        community.setCommunityName(txtViewCommunity.getText());
//        JOptionPane.showMessageDialog(this, "Successfully Saved");
//        txtViewCommunity.setText("");
        
        if (txtViewCommunity.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter a Community name");
            return;
        }
        
        if (txtViewCommunity.getText().matches(regxCommunityName)){
            
            
            community.setCommunityName(txtViewCommunity.getText());
            JOptionPane.showMessageDialog(this, "Successfully Saved");
            txtViewCommunity.setText("");

        }
        else{
            JOptionPane.showMessageDialog(this, "Enter a valid Community Name\nOnly alphabets and spaces allowed");
        }
        
    }//GEN-LAST:event_btnUpdateCommunityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        displayJPanel.remove(this);
        Component[] componentArray = displayJPanel.getComponents();
        Component component = componentArray[componentArray.length-1];
        CommunityJPanel communityJPanel = (CommunityJPanel) component;
        communityJPanel.populateTable();
        CardLayout cardLayout = (CardLayout) displayJPanel.getLayout();
        cardLayout.previous(displayJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateCommunity;
    private javax.swing.JLabel communityNameJLabel;
    private javax.swing.JTextField txtViewCommunity;
    private javax.swing.JLabel viewCommunityJLabel;
    // End of variables declaration//GEN-END:variables
}
